/**
 * Mock data — replicar formato esperado dos endpoints futuros do backend.
 * Cobre tudo que o pipeline produz + comparativo de mercado (que viria
 * de scraping/APIs Zap/VivaReal/etc consolidado por LLM, fase futura).
 */

export const MOCK_PROPERTIES = [
  {
    id: 1,
    numero_imovel: '8787701603694',
    endereco_short: 'R. José de Alcântara, 765 — apto 34',
    endereco_full: 'RUA JOSE DE ALCANTARA, N. 765 APTO. 34 TORRE 4 - BLOCO A, JARDIM HEITOR RIGON, RIBEIRAO PRETO - SP, 14062-100',
    bairro: 'Jardim Heitor Rigon',
    cidade: 'Ribeirão Preto', uf: 'SP', cep: '14062-100',
    tipo_imovel: 'apartamento',
    nome_empreendimento: 'VITTA HEITOR RIGON 3',
    modalidade_short: 'Venda direta',
    situacao: 'desocupado',
    quartos: 2, banheiros: 1, vagas: 1,
    area_total_m2: 89.45, area_privativa_m2: 43.06, area_construida_m2: 67.30,
    preco_venda: 82529, valor_avaliacao: 174084, desconto_percentual: 52.6,
    aceita_fgts: true, aceita_financiamento: true,
    bairro_score: 72,
    riscos_juridicos: [],
    matricula_numero: '195017', comarca: 'RIBEIRAO PRETO-SP', oficio: '01',
    averbacao_leiloes_negativos: true,
    lat: -21.1574, lon: -47.8147,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=600&q=70',
    formas_pagamento: ['Recursos próprios', 'Permite utilização de FGTS'],
    regras_despesas: {
      condomínio: 'Sob responsabilidade do comprador, até o limite de 10% em relação ao valor de avaliação',
      tributos: 'Sob responsabilidade do comprador',
    },
    link_matricula_pdf: '/editais/matricula/SP/8787701603694.pdf',
    ai_score: 84, ai_recomendacao: 'comprar',
    ai_roi_estimado: '9% a 12% ao ano',
    ai_estrategia: 'Reforma leve + locação anual',
    ai_pros: ['Desconto de 52,6% sobre avaliação', 'Imóvel desocupado — entrega imediata', 'Aceita FGTS e financiamento Caixa'],
    ai_riscos: ['Verificar débitos condominiais antes da proposta'],
    bairro_eval: {
      score: 72,
      justificativa: 'Jardim Heitor Rigon é uma região consolidada de Ribeirão Preto com infraestrutura completa, comércio local ativo e boa oferta de transporte público.',
      pontos_fortes: ['Comércio local forte', 'Acesso a escolas e UBS', 'Linhas de ônibus frequentes'],
      pontos_fracos: ['Trânsito intenso em horários de pico', 'Pouca área verde'],
      perfil_recomendado: 'famílias jovens e investidores de aluguel',
      preco_m2_medio: 4380, amostra_n: 23,
    },
    matricula: {
      donos_atuais: [{ nome: 'CAIXA ECONÔMICA FEDERAL', cpf_cnpj: '00.360.305/0001-04' }],
      donos_anteriores: [
        { nome: 'JOSÉ MARIA DA SILVA', data_aquisicao: '2014-08-12', data_alienacao: '2022-03-04' },
        { nome: 'CONSTRUTORA VITTA EMPREENDIMENTOS LTDA', data_aquisicao: '2009-05-20', data_alienacao: '2014-08-12' },
      ],
      ano_construcao_estimado: 2010,
      vendas_anteriores: [
        { data: '2014-08-12', valor: 195000, vendedor: 'Construtora Vitta', comprador: 'José M. da Silva' },
        { data: '2022-03-04', valor: 168000, vendedor: 'José M. da Silva', comprador: 'Caixa Econômica Federal' },
      ],
    },
    mercado_similar: {
      preco_medio: 318000, preco_min: 285000, preco_max: 365000,
      amostra_n: 13,
      criterio: 'Apto 2q · 80–100m² · raio 1km de Jardim Heitor Rigon',
      fontes: [
        { nome: 'Zap Imóveis', n: 8 },
        { nome: 'Viva Real', n: 5 },
      ],
      ultimo_update: '2026-05-09T10:00:00Z',
    },
    watchers: 4200, favorited: false,
  },
  {
    id: 2,
    numero_imovel: '8444433039915',
    endereco_short: 'Cruzeirão — casa 3 quartos',
    endereco_full: 'CRUZEIRO DO SUL - CRUZEIRÃO',
    bairro: 'Cruzeirão', cidade: 'Cruzeiro do Sul', uf: 'AC',
    tipo_imovel: 'casa', modalidade_short: 'Leilão SFI',
    situacao: 'ocupado',
    quartos: 3, banheiros: 2, vagas: 2,
    area_total_m2: 115.5, area_construida_m2: 92.4,
    preco_venda: 98000, valor_avaliacao: 195000, desconto_percentual: 49.7,
    aceita_fgts: false, aceita_financiamento: true,
    bairro_score: 58, matricula_numero: '9020',
    riscos_juridicos: ['gravame', 'penhora', 'regularizacao_adquirente'],
    riscos_juridicos_raw: 'Imóvel com gravame/penhora/indisponibilidade averbada na matrícula. Regularização por conta do adquirente.',
    lat: -7.6353, lon: -72.6702,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=600&q=70',
    formas_pagamento: ['Recursos próprios', 'Financiamento - somente SBPE'],
    regras_despesas: { condomínio: 'Sob responsabilidade do comprador', tributos: 'Sob responsabilidade do comprador' },
    link_matricula_pdf: '/editais/matricula/AC/8444433039915.pdf',
    link_edital_pdf: '/editais/EL00240226CPARE.PDF',
    link_pregoeiro: 'https://www.gestordeleiloes.com.br',
    nome_leiloeiro: 'EDUARDO DE WERK',
    edital: '0024/0226 - CPA/RE',
    data_leilao_1: '2026-06-09T13:00:00Z',
    data_leilao_2: '2026-06-15T13:00:00Z',
    valor_leilao_1: 173929, valor_leilao_2: 125363,
    ai_score: 68, ai_recomendacao: 'analisar',
    ai_roi_estimado: '7% a 10% ao ano',
    ai_estrategia: 'Aguardar 2º leilão se possível',
    ai_pros: ['Casa com 3 quartos e 2 vagas', 'Cidade em desenvolvimento'],
    ai_riscos: ['Imóvel ocupado — desocupação pode demorar', 'Liquidez baixa em revenda no AC'],
    bairro_eval: {
      score: 58,
      justificativa: 'Cruzeirão é bairro residencial periférico de Cruzeiro do Sul com infraestrutura básica.',
      pontos_fortes: ['Lotes amplos', 'Tranquilidade'],
      pontos_fracos: ['Distância do centro', 'Comércio limitado', 'Liquidez baixa'],
      perfil_recomendado: 'compradores para uso próprio',
      preco_m2_medio: 1860, amostra_n: 8,
    },
    matricula: {
      donos_atuais: [{ nome: 'CAIXA ECONÔMICA FEDERAL', cpf_cnpj: '00.360.305/0001-04' }],
      donos_anteriores: [{ nome: 'ANTONIO PEREIRA DOS SANTOS', data_aquisicao: '2017-11-03', data_alienacao: '2024-09-18' }],
      ano_construcao_estimado: 2015,
      vendas_anteriores: [{ data: '2017-11-03', valor: 142000, vendedor: 'Construtora local', comprador: 'A. Pereira dos Santos' }],
    },
    mercado_similar: {
      preco_medio: 220000, preco_min: 180000, preco_max: 260000,
      amostra_n: 5,
      criterio: 'Casa 3q · 100–140m² · Cruzeiro do Sul',
      fontes: [{ nome: 'Zap Imóveis', n: 3 }, { nome: 'OLX', n: 2 }],
      ultimo_update: '2026-05-09T10:00:00Z',
      confianca: 'baixa',
    },
    watchers: 380,
  },
  {
    id: 3,
    numero_imovel: '8787714892088',
    endereco_short: 'Cond. Belleville — apto 303',
    endereco_full: 'ALAMEDA GOIAS, N. SN APTO. 303 BL E LT 83-A, MANSOES CENTRO OESTE, AGUAS LINDAS DE GOIAS - GO',
    bairro: 'Mansões Centro Oeste', cidade: 'Águas Lindas de Goiás', uf: 'GO',
    tipo_imovel: 'apartamento', nome_empreendimento: 'COND RES BELLEVILE',
    modalidade_short: 'Leilão SFI', situacao: 'ocupado',
    quartos: 2, banheiros: 1, vagas: 1, area_total_m2: 102.68, area_privativa_m2: 59.97,
    preco_venda: 173929, valor_avaliacao: 225000, desconto_percentual: 22.7,
    aceita_fgts: true, aceita_financiamento: true,
    bairro_score: 64, matricula_numero: '86033',
    lat: -15.7521, lon: -48.2810,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=600&q=70',
    formas_pagamento: ['Recursos próprios', 'FGTS'],
    regras_despesas: { condomínio: 'Sob responsabilidade do comprador', tributos: 'Sob responsabilidade do comprador' },
    link_matricula_pdf: '/editais/matricula/GO/8787714892088.pdf',
    link_edital_pdf: '/editais/EL00240226CPARE.PDF',
    link_pregoeiro: 'https://www.gestordeleiloes.com.br',
    nome_leiloeiro: 'EDUARDO DE WERK',
    data_leilao_1: '2026-05-13T13:00:00Z',
    data_leilao_2: '2026-05-20T13:00:00Z',
    valor_leilao_1: 225000, valor_leilao_2: 173929,
    ai_score: 71, ai_recomendacao: 'comprar',
    ai_roi_estimado: '8% a 11% ao ano',
    ai_estrategia: 'Aguardar 2º leilão',
    ai_pros: ['Cidade-dormitório de Brasília', 'Boa demanda de aluguel'],
    ai_riscos: ['Ocupado', 'Custos de desocupação'],
    bairro_eval: {
      score: 64,
      justificativa: 'Mansões Centro Oeste é polo residencial em expansão. Demanda forte por aluguel pela proximidade com Brasília.',
      pontos_fortes: ['Proximidade a Brasília', 'Comércio crescendo'],
      pontos_fracos: ['Trânsito pra DF nos picos'],
      perfil_recomendado: 'investidores de aluguel',
      preco_m2_medio: 2890, amostra_n: 41,
    },
    mercado_similar: {
      preco_medio: 285000, preco_min: 245000, preco_max: 320000,
      amostra_n: 18,
      criterio: 'Apto 2q · 90–110m² · Águas Lindas de Goiás',
      fontes: [{ nome: 'Zap Imóveis', n: 11 }, { nome: 'Viva Real', n: 7 }],
      ultimo_update: '2026-05-09T10:00:00Z',
    },
    watchers: 1100,
  },
  {
    id: 4,
    numero_imovel: '10005120',
    endereco_short: 'R. do Purus, lote 10',
    endereco_full: 'RUA DO PURUS, N. S/N QUARTEIRÃO 272, LOTE 10, BAIRRO COHAB, CRUZEIRO DO SUL - AC',
    bairro: 'Cohab', cidade: 'Cruzeiro do Sul', uf: 'AC',
    tipo_imovel: 'terreno', modalidade_short: 'Venda direta', situacao: 'desocupado',
    area_terreno_m2: 600,
    preco_venda: 66169, valor_avaliacao: 150000, desconto_percentual: 55.9,
    aceita_fgts: false, aceita_financiamento: true,
    bairro_score: 41, matricula_numero: '9740',
    lat: -7.6280, lon: -72.6680,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=70',
    formas_pagamento: ['Recursos próprios', 'Financiamento - somente SBPE'],
    regras_despesas: { tributos: 'Sob responsabilidade do comprador' },
    link_matricula_pdf: '/editais/matricula/AC/0000010005120.pdf',
    ai_score: 52, ai_recomendacao: 'analisar',
    ai_roi_estimado: 'Especulação — 5% a 8% a.a.',
    ai_estrategia: 'Compra para construção própria',
    ai_pros: ['Terreno amplo (600m²)', 'Desconto agressivo'],
    ai_riscos: ['Liquidez muito baixa', 'Não tem benfeitorias'],
    bairro_eval: {
      score: 41,
      justificativa: 'Cohab é loteamento periférico com infra incompleta. Investimento de longo prazo apenas.',
      pontos_fortes: ['Lotes baratos'],
      pontos_fracos: ['Sem pavimentação completa', 'Infraestrutura precária'],
      perfil_recomendado: 'autoconstrutores',
      preco_m2_medio: 110, amostra_n: 12,
    },
    mercado_similar: {
      preco_medio: 95000, preco_min: 70000, preco_max: 130000,
      amostra_n: 4,
      criterio: 'Terreno 500–700m² · Cruzeiro do Sul periferia',
      fontes: [{ nome: 'OLX', n: 3 }, { nome: 'Imovelweb', n: 1 }],
      ultimo_update: '2026-05-09T10:00:00Z',
      confianca: 'baixa',
    },
    watchers: 95,
  },
  {
    id: 5,
    numero_imovel: '8444426198310',
    endereco_short: 'R. Hortência Ribeiro, 485',
    endereco_full: 'RUA HORTENCIA RIBEIRO DA SILVA, N. 485 APTO. 102B, TRES IRMAS, CAMPINA GRANDE - PB',
    bairro: 'Três Irmãs', cidade: 'Campina Grande', uf: 'PB',
    tipo_imovel: 'apartamento',
    nome_empreendimento: 'EDIFICIO RESIDENCIAL PORTAL DAS HORTENSIAS',
    modalidade_short: 'Venda direta', situacao: 'ocupado',
    quartos: 2, banheiros: 1, vagas: 1, area_total_m2: 46.5, area_privativa_m2: 42.09,
    preco_venda: 72500, valor_avaliacao: 148000, desconto_percentual: 51.0,
    aceita_fgts: true, aceita_financiamento: true,
    bairro_score: 67, matricula_numero: '146330',
    lat: -7.2392, lon: -35.9026,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=600&q=70',
    formas_pagamento: ['Recursos próprios', 'FGTS'],
    link_matricula_pdf: '/editais/matricula/PB/8444426198310.pdf',
    ai_score: 78, ai_recomendacao: 'comprar',
    ai_roi_estimado: '10% a 13% ao ano',
    ai_estrategia: 'Reforma + locação universitária',
    ai_pros: ['Cidade universitária — alta demanda de aluguel', 'Desconto 51%'],
    ai_riscos: ['Ocupado', 'Apto compacto'],
    bairro_eval: {
      score: 67,
      justificativa: 'Três Irmãs é bairro residencial próximo à UFCG. Forte demanda estudantil.',
      pontos_fortes: ['Próximo à UFCG', 'Comércio local', 'Mercado de aluguel ativo'],
      pontos_fracos: ['Lotes pequenos'],
      perfil_recomendado: 'investidores de aluguel estudantil',
      preco_m2_medio: 2640, amostra_n: 17,
    },
    mercado_similar: {
      preco_medio: 165000, preco_min: 140000, preco_max: 195000,
      amostra_n: 9,
      criterio: 'Apto 2q · 40–60m² · Três Irmãs',
      fontes: [{ nome: 'Zap Imóveis', n: 5 }, { nome: 'OLX', n: 4 }],
      ultimo_update: '2026-05-09T10:00:00Z',
    },
    watchers: 720,
  },
  {
    id: 6,
    numero_imovel: '8787712353201',
    endereco_short: 'Total Ville Pitangueiras',
    endereco_full: 'QUADRA QC 01, N. SN APTO. 102 BL 28, CIDADE JARDINS - VALPARAISO DE GOIAS - GO',
    bairro: 'Cidade Jardins', cidade: 'Valparaíso de Goiás', uf: 'GO',
    tipo_imovel: 'apartamento', nome_empreendimento: 'TOTAL VILLE PITANGUEIRAS',
    modalidade_short: 'Licitação aberta', situacao: 'ocupado',
    quartos: 2, banheiros: 1, area_total_m2: 93.59, area_privativa_m2: 50.84,
    preco_venda: 88697, valor_avaliacao: 151500, desconto_percentual: 41.5,
    aceita_fgts: true, aceita_financiamento: true,
    bairro_score: 55, matricula_numero: '99250',
    lat: -16.0656, lon: -47.9762,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=600&q=70',
    formas_pagamento: ['Recursos próprios', 'FGTS'],
    link_matricula_pdf: '/editais/matricula/GO/8787712353201.pdf',
    link_edital_pdf: '/editais/EA00040326CPVERE.PDF',
    link_pregoeiro: 'https://simonleiloes.com.br',
    nome_leiloeiro: 'ELTON LUIZ SIMON',
    edital: '0004/0326 - CPVE/RE', numero_item: '62',
    data_leilao_1: '2026-05-13T13:00:00Z',
    ai_score: 65, ai_recomendacao: 'analisar',
    ai_roi_estimado: '7% a 10% ao ano',
    ai_pros: ['Edital aberto — possibilidade de lance baixo'],
    ai_riscos: ['Ocupado', 'Disputa pode subir o preço'],
    bairro_eval: {
      score: 55,
      justificativa: 'Cidade Jardins atende demanda de funcionários públicos do DF.',
      pontos_fortes: ['Próximo a Brasília', 'Comércio em expansão'],
      pontos_fracos: ['Trânsito pesado em horários de pico'],
      perfil_recomendado: 'investidores de aluguel',
      preco_m2_medio: 2400, amostra_n: 22,
    },
    mercado_similar: {
      preco_medio: 195000, preco_min: 165000, preco_max: 240000,
      amostra_n: 15,
      criterio: 'Apto 2q · 80–100m² · Valparaíso de Goiás',
      fontes: [{ nome: 'Zap Imóveis', n: 9 }, { nome: 'Viva Real', n: 6 }],
      ultimo_update: '2026-05-09T10:00:00Z',
    },
    watchers: 540,
  },
]

export const MOCK_FILTER_OPTIONS = {
  modalidades: [
    { value: 'venda_direta', label: 'Venda direta' },
    { value: 'leilao_sfi', label: 'Leilão SFI' },
    { value: 'licitacao', label: 'Licitação aberta' },
    { value: 'venda_online', label: 'Venda online' },
  ],
  ufs: ['SP', 'RJ', 'MG', 'PB', 'GO', 'AC', 'PE'].map((u) => ({ value: u, label: u })),
  cidades: ['Ribeirão Preto', 'Cruzeiro do Sul', 'Águas Lindas de Goiás', 'Campina Grande', 'Valparaíso de Goiás'].map((c) => ({ value: c, label: c })),
  bairros: ['Jardim Heitor Rigon', 'Cruzeirão', 'Mansões Centro Oeste', 'Cohab', 'Três Irmãs', 'Cidade Jardins'].map((b) => ({ value: b, label: b })),
}
