name: Auto Merge Codex PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  auto-merge:
    if: |
      github.actor == 'github-actions[bot]' ||
      github.actor == 'codex[bot]' ||
      github.actor == 'codex-app[bot]' ||
      contains(github.event.pull_request.labels.*.name, 'codex')
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

      - name: Auto-merge PR
        uses: peter-evans/auto-merge@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
